config/routes.rb
Noobnoos::Application.routes.draw do
  devise_for :users

  resources :pages
  resources :links do
    member do
      post :vote_up
      post :vote_down
    end
    resources :comments do
      member do
        post :vote_up
        post :vote_down
      end
    end
  end

  match  '/links/:id/favorite' => 'links#favorite'
  get '/mylinks' => 'links#userlinks', as: 'user_links'
  get '/favorites' => 'links#favorites', as: 'favorite_links'
  get '/tags/:id'  => 'links#taglinks', as: 'tag'
  root :to => 'links#index'

end

app/models/link.rb
class Link < ActiveRecord::Base
  include Simplificator::Webthumb

  acts_as_voteable

  attr_accessible :title, :url, :description, :thumbnail, :previewtext, :tag_ids
  belongs_to :user
  has_many :comments
  has_many :favorites
  has_many :taggings
  has_many :tags, through: :taggings

  scope :by_score, joins("LEFT OUTER JOIN votes ON links.id = votes.voteable_id AND votes.voteable_type = 'Link'").
                   group('links.id').
                   order('SUM(CASE votes.vote WHEN true THEN 1 WHEN false THEN -1 ELSE 0 END) DESC')

  #add to sunspot search index
  searchable do
    text :title
  end

  after_create :add_thumbnail

  after_create :add_preview_text

  def add_thumbnail
    wt = Webthumb.new('099811cd90ed3133d359f06edd87db46')
    job = wt.thumbnail(:url => self.url)
    filename = File.join(Rails.root, 'tmp', self.title + '.jpg')
    job.write_file(job.fetch_when_complete(:large), filename)

    

    # Upload to S3
    file = Rails.application.config.storage_dir.files.create(
      #key is title.jpg of url
      :key    => filename.split('/').last,
      :body   => File.open(filename),
      :public => true
    )

    self.thumbnail = file.public_url

    self.save
  end

  def add_preview_text
    if self.description.length < 200
      self.previewtext = self.description
      self.save
    else
      words = self.description.split(" ")
      preview = ""
      words.each do |word|
        preview +=" " + word if preview.length + word.size < 200
      end
      preview+="..."
      self.previewtext = preview
      self.save
    end
  end

  # TAGGING CATEGORIES
  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) AS COUNT").joins(:taggings).group("taggings.tag_id")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

  def tag_ids=(tag_ids)
    if self.persisted?
      self.taggings.destroy_all
      tag_ids.each do |tag_id|
        self.taggings.create(tag_id: tag_id) unless tag_id.blank?
      end
    else
      tag_ids.each do |tag_id|
        self.taggings.build(tag_id: tag_id)
      end
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :authenticate_user!, only: [:vote_up, :vote_down, :create, :favorite]

  # ALL LINKS
  def index
    params[:page] ||=1
    params[:per_page] ||=7

    @search = Link.search do 
      fulltext params[:search]
    end
    @result = @search.results

    if params[:search]
      @links = @result
    else
      @links = Link.by_score.page(params[:page].to_i).per_page(params[:per_page].to_i)
    end
  end

  # SINGLE LINK
  def show
    @link = Link.find(params[:id])
    @comments = @link.comments.sort_by {|comment| comment.plusminus}.reverse
    @new_comment = @link.comments.build(params[:comment])
  end

  # NEW LINK
  def new
    @link = Link.new
  end

  # CREATE LINK 
  def create
    @link = Link.new(params[:link])
    @link.user = current_user

    if @link.save
      redirect_to @link
    else
      render :new
    end
  end

  # EDIT LINK
  def edit
    @link = Link.find(params[:id])
  end

  # UPDATE LINK
  def update
    @link = Link.find(params[:id])
    if @link.update_attributes(params[:link])
      redirect_to(@link)
    else
      render :edit
    end
  end

  # USERS LINKS
  def userlinks
    params[:page] ||=1
    params[:per_page] ||=5
    # Only show the links that the current user has submitted, in order of upvote count.
    @links = Link.where(user_id: current_user.id).plusminus_tally.order('plusminus_tally ASC').page(params[:page].to_i).per_page(params[:per_page].to_i)
    render action: 'index'
  end

  def taglinks
    params[:page] ||=1
    params[:per_page] ||=5

    @links = Tag.find_by_name(params[:id]).links.plusminus_tally.order('plusminus_tally ASC').page(params[:page].to_i).per_page(params[:per_page].to_i)
    render action: 'index'
  end

  # VOTE LINK UP
  def vote_up
    begin
      current_user.vote_exclusively_for(@link = Link.find(params[:id]))
      redirect_to :back
    rescue ActiveRecord::RecordInvalid
      redirect_to :back
    end
  end

  # VOTE LINK DOWN
  def vote_down
    begin
      current_user.vote_exclusively_against(@link = Link.find(params[:id]))
      redirect_to :back
    rescue ActiveRecord::RecordInvalid
      redirect_to :back
    end
  end

  # ADD OR REMOVE LINK FROM USER FAVORITES 
  def favorite
    if Favorite.where(user_id: current_user.id, link_id: params[:id]).exists?
      Favorite.where(user_id: current_user.id, link_id: params[:id]).destroy_all
    else
      Favorite.create(user_id: current_user.id, link_id: params[:id])
    end
    redirect_to :back
  end

  # INDEX OF USER'S FAVORITE LINKS
  def favorites
    params[:page] ||=1
    params[:per_page] ||=5
    @links = Link.where("Links.id IN (?) ", current_user.favorites).plusminus_tally.order('plusminus_tally ASC').page(params[:page].to_i).per_page(params[:per_page].to_i)
    render action: 'index'
  end
  
  # DESTROY LINK
  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to root_url
  end
end

app/helpers/links_helper.rb
module LinksHelper

  def show_favorite_star(user, link)
    #default favorite_star classes
    favorite_classes = "icon-star icon-large"

    unless current_user.present?
      link_to raw("<i class='#{favorite_classes + " icon-muted"}'></i>"), new_user_session_path
    else
    #if the link is NOT a favorite for the user, add class to make the star gray.
    favorite_classes += " icon-muted" if !Favorite.exists?(user_id: user.id, link_id: link.id)
    #display the star with the correct classes. 
    link_to_function raw("<i class='#{favorite_classes}'></i>"), "$.ajax({url:'/links/#{link.id}/favorite', type: 'PUT'});"
    end
  end

  def nav_link(title, link_path)
    link_classes = current_page?(link_path) ? 'active' : ''

    content_tag(:li, class: link_classes) do
      link_to title, link_path
    end
  end

end

app/views/links/_comment.html.haml
-if comment.message !=nil
  .comment.row
    .small-2.columns.span-comment-vote
      %div
        = link_to raw('<i class="icon-caret-up icon-large myvotearrow"></i>'), vote_up_link_comment_path(link, comment), :method => :post
      %div
        %h4.votes=comment.plusminus
      %div
        = link_to raw('<i class="icon-caret-down icon-large myvotearrow"></i>'), vote_down_link_comment_path(link, comment), :method => :post
      
    .small-22.columns.comment-content    
      %p
        %span.user
          %strong="User:" if comment.user
          = comment.user.username if comment.user
        %span.date
          %strong="Date:" if comment.created_at
          - localcommenttime = comment.created_at-5.hours if comment.created_at
          = localcommenttime.strftime("%D %I:%M %p") if comment.created_at
        %div
          %p= comment.message

app/views/links/edit.html.haml
/ %h2=params
.row
  .small-24.columns.mysign-in-header EDIT A LINK!
.row.myform
  .small-24.large-14.columns.large-offset-6
    =form_for(@link) do |f|
      -if @link.errors.any?
        #error_explanation
          %h2= pluralize(@link.errors.count, "error") + "prohibited this link from being saved:"
          %ul
            - @link.errors.full_messages.each do |msg|
              %li= msg
      .row
        .large-20.columns
          .form-field.input-container.large-24.columns
            = f.text_field :title, :placeholder => "Title", :autofocus => true
          .form-field.input-container.large-24.columns
            = f.text_field :url, :placeholder => "Link"
          .form-field.input-container.large-24.columns
            = f.text_area :description, :placeholder => "Description", rows: "10"
        .form-field.input-container.large-4.columns.tags
          = collection_select :link, :tag_ids, Tag.all(order: "name ASC"), :id, :name, {include_blank: true}, { :multiple => true, :class => :selectTags}
      .row
        .small-24.columns.small-offset-7
          = f.submit "Update Link", :class => 'button mylink-button'
  / = render "devise/shared/links"

app/views/links/index.html.haml
/ %h2=params
.row.myheader
  =image_tag("NOOBNOOS_TITLE.png", class: "myheader")
.row
  .small-19.columns
    -@links.sort_by {|link| link.plusminus}.reverse.each do |link|
      .row.mylinkspace.multiple
        .small-2.columns.span-link-vote
          = link_to vote_up_link_path(link), :method => :post do
            %i.icon-caret-up.icon-4x.myvotearrow
          %div
            %h1.votes=link.plusminus
          = link_to vote_down_link_path(link), :method => :post do
            %i.icon-caret-down.icon-4x.myvotearrow
        .link_border.small-22.columns
          .small-5.columns.mythumbnail
            =link_to image_tag(link.thumbnail, class: "thumbnail mythumbnail"), link.url
          .small-16.columns.small-offset-2
            %h5
              %strong.linktitle=link_to link.title, link    
            %p.tags=raw link.tags.map(&:name).map { |t| link_to t, tag_path(t)}.join(' | ') 
            %p.previewtext=link.previewtext
            %p.aboutlink
              -gravatar_hash = Digest::MD5.hexdigest(link.user.email.downcase)
              =image_tag("http://www.gravatar.com/avatar/" + gravatar_hash, class: "userthumb")
              %span.blue
                =link.user.username
              | 
              %i.icon-calendar
              -localtime = link.created_at-5.hours
              = localtime.strftime("%D %I:%M %p")
              |
              = link_to "#{link.comments.count} #{'comment'.pluralize(link.comments.count)}", link
              |
              = show_favorite_star(current_user, link)
    .row.paginating
      %div.pagination-centered
        = foundation_paginate(@links)
  .small-4.columns.small-offset-1.tagcloud
    .tag.tag-title
      %h5
        TAGS
    - Tag.all.map(&:name).each do |t|
      .tag
        = link_to t, tag_path(t)



app/views/links/new.html.haml
/ %h2=params
.row
  .small-24.columns.mysign-in-header ADD A LINK!
.row.myform
  .small-24.large-14.columns.large-offset-6
    =form_for(@link) do |f|
      -if @link.errors.any?
        #error_explanation
          %h2= pluralize(@link.errors.count, "error") + "prohibited this link from being saved:"
          %ul
            - @link.errors.full_messages.each do |msg|
              %li= msg
      .row
        .large-20.columns
          .form-field.input-container.large-24.columns
            = f.text_field :title, :placeholder => "Title", :autofocus => true
          .form-field.input-container.large-24.columns
            = f.text_field :url, :placeholder => "Link"
          .form-field.input-container.large-24.columns
            = f.text_area :description, :placeholder => "Description", rows: "10"
        .form-field.input-container.large-4.columns.tags
          = collection_select :link, :tag_ids, Tag.all(order: "name ASC"), :id, :name, {include_blank: true}, { :multiple => true, :class => :selectTags}
      .row
        .small-24.columns.small-offset-7
          = f.button "Add Link", :class => 'button mylink-button'
  / = render "devise/shared/links"

app/views/links/show.html.haml
/ %h2=params
.row.show.mylinkspace
  .small-2.columns.span-link-vote
    = link_to vote_up_link_path(@link), :method => :post do
      %i.icon-caret-up.icon-4x.myvotearrow
    %div
      %h1.votes=@link.plusminus
    = link_to vote_down_link_path(@link), :method => :post do
      %i.icon-caret-down.icon-4x.myvotearrow
  .link
    .small-9.columns.mythumbnail
      =link_to image_tag(@link.thumbnail, class: "thumbnail mythumbnail show"), @link.url
    .small-13.columns
      %h4
        %strong.linktitle=link_to @link.title, @link.url     
      %p.tags=raw @link.tags.map(&:name).map { |t| link_to t, tag_path(t)}.join(' // ') 
      %p=@link.description
      %p.aboutlink
        -gravatar_hash = Digest::MD5.hexdigest(@link.user.email.downcase)
        =image_tag("http://www.gravatar.com/avatar/" + gravatar_hash, class: "userthumb")
        %span.blue
          =@link.user.username
        | 
        %i.icon-calendar
        -localtime = @link.created_at-5.hours
        = localtime.strftime("%D %I:%M %p")
        - if current_user == @link.user
          |
          = link_to "Edit Link", edit_link_path(@link)
          |
          = link_to "Delete Link", @link, confirm: "Are you sure?",method: "delete"
          |
          = show_favorite_star(current_user, 
            @link)
.row.mylinkspace
  .small-13.columns.comments
    %h4.comment-header Comments:
    = render :partial => "comment", locals: {link: @link}, collection: @comments
  .small-11.columns.myform
    .row
      .large-20.columns
        = form_for([@link, @new_comment], :remote => true) do |f|
          -if @new_comment.errors.any?
            #error_explanation
              %h2= pluralize(@new_comment.errors.count, "error") + "prohibited this comment from being saved:"
              %ul
                - @new_comment.errors.full_messages.each do |msg|
                  %li= msg
          %div= f.text_area :message, :placeholder => "Add a comment!", :autofocus => true, rows: "14", class: "small-16 columns"
          .row
            .small-12.columns.small-offset-4
              %div= f.submit "Add Comment", :class => 'button small'