config/routes.rb
Noobnoos::Application.routes.draw do
  devise_for :users

  resources :pages
  resources :links do
    member do
      post :vote_up
      post :vote_down
    end
    resources :comments do
      member do
        post :vote_up
        post :vote_down
      end
    end
  end

  match  '/links/:id/favorite' => 'links#favorite'
  get '/mylinks' => 'links#userlinks', as: 'user_links'
  get '/favorites' => 'links#favorites', as: 'favorite_links'
  get '/tags/:id'  => 'links#taglinks', as: 'tag'
  root :to => 'links#index'

end

app/views/layouts/application.html.haml
!!! 5
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class=\"ie6\" lang=\"en\">
/[if IE 7 ]    <html class=\"ie7\" lang=\"en\">
/[if IE 8 ]    <html class=\"ie8\" lang=\"en\">
/[if IE 9 ]    <html class=\"ie9\" lang=\"en\">
/[if (gt IE 9)|!(IE)] <!--> <html lang=\"en\">

%head
  %meta{ :charset => "utf-8" }

  -# Set the viewport width to device width for mobile
  %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

  %title NoobNoos
  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tag
  %link(href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet")
  %link(href="http://fonts.googleapis.com/css?family=Fauna+One|Antic|Antic+Slab" rel="stylesheet" type="text/css")

%body
  .fixed
    %nav.top-bar
      %ul.title-area
        %li.name
          %h1
            %a(href="/") n00bn00s
        %li.toggle-topbar.menu-icon
          %a(href="#")
            %span Menu
      %section.top-bar-section
        %ul.left
          %li.divider
          = nav_link "Home", root_path
          - if current_user.present?
            %li.divider
            = nav_link "Add a Link", new_link_path
            %li.divider
            = nav_link "See All Your Links", user_links_path
            %li.divider
            = nav_link "Favorites", favorite_links_path
          - else
            %li.divider
            = nav_link "Sign In", new_user_session_path
            %li.divider
            = nav_link "Register Now!", new_user_registration_path
        %ul.right
          %li.divider
          %li.search
            =form_tag root_url, method: "get" do
              %li.searchfield= text_field_tag :search, params[:search]
              %li.searchbutton= submit_tag "Search", class: "button mysearchbutton"
          %li.has-dropdown
            - if current_user.present?
              %a(href="#")
                - gravatar_hash = Digest::MD5.hexdigest(current_user.email.downcase)
                = image_tag("http://www.gravatar.com/avatar/" + gravatar_hash, class: "userthumb-mini")
                = current_user.username
            - else
              %a(href="#")
                %i.icon-user=" Menu"
            %ul.dropdown
              - if current_user.present?
                / %li=link_to "Profile", profile_path(current_user.profile)
              - else
                %li= link_to "Sign In", new_user_session_path
              %li.divider
              %li
                %a(tabindex="-1" href="http://sdrioux.github.io") About Me
              %li
                %a(tabindex="-1" href="https://github.com/sdrioux/noobnoos.git") Source Code
              - if current_user.present?
                %li.divider
                %li= link_to "Sign Out", destroy_user_session_path, method: "delete", tabindex: "-1"
- if flash[:notice]
  .alert-box=notice
- if flash[:alert]
  .alert-box=alert
.container
  = yield

  = javascript_include_tag "application"

.footer
  %ul.footerlinks
    %li
      %a(href="http://sdrioux.github.io") About Me
    |
    %li
      %a(href="https://github.com/sdrioux/noobnoos.git") Source Code